; Listing generated by Microsoft (R) Optimizing Compiler Version 19.42.34435.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp_malloc:PROC
EXTRN	__imp___stdio_common_vfscanf:PROC
EXTRN	__imp_CreateThread:PROC
EXTRN	__imp_system:PROC
EXTRN	__imp_Sleep:PROC
EXTRN	__imp___stdio_common_vfprintf:PROC
EXTRN	__imp___acrt_iob_func:PROC
EXTRN	__security_check_cookie:PROC
$SG4294967289 DB 'Value at the pointer [%p] is -> [%d] ', 0aH, 00H
	ORG $+1
$SG4294967288 DB 'CLS', 00H
$SG4294967286 DB '%d', 00H
	ORG $+1
$SG4294967287 DB 'Size to allocate -> ', 00H
	ORG $+3
$SG4294967285 DB 'Allocated [%d] bytes at [%p]', 0aH, 00H
	ORG $+2
$SG4294967284 DB 'Value to give the pointer at [%p] -> ', 00H
	ORG $+2
$SG4294967283 DB '%d', 00H
CONST	ENDS
PUBLIC	main
PUBLIC	?init@@YAXPEAH@Z				; init
PUBLIC	?test@@YAXPEAH@Z				; test
PUBLIC	scanf_s
PUBLIC	_vfscanf_s_l
PUBLIC	printf
PUBLIC	_vfprintf_l
PUBLIC	__local_stdio_scanf_options
PUBLIC	__local_stdio_printf_options
PUBLIC	?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	__GSHandlerCheck:PROC
EXTRN	__security_cookie:QWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN3@main
	DD	imagerel $LN3@main+161
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?init@@YAXPEAH@Z DD imagerel $LN3@init
	DD	imagerel $LN3@init+54
	DD	imagerel $unwind$?init@@YAXPEAH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?test@@YAXPEAH@Z DD imagerel $LN6
	DD	imagerel $LN6+66
	DD	imagerel $unwind$?test@@YAXPEAH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$scanf_s DD imagerel $LN3@scanf_s
	DD	imagerel $LN3@scanf_s+113
	DD	imagerel $unwind$scanf_s
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfscanf_s_l DD imagerel $LN3@vfscanf_s_
	DD	imagerel $LN3@vfscanf_s_+75
	DD	imagerel $unwind$_vfscanf_s_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN3@printf
	DD	imagerel $LN3@printf+116
	DD	imagerel $unwind$printf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN3@vfprintf_l
	DD	imagerel $LN3@vfprintf_l+68
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DQ 00000621800011801r	; 5.32876e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DQ 00000821800012719r		; 7.06709e-310
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfscanf_s_l DQ 00000621800011801r	; 5.32876e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$scanf_s DQ 00000821800012719r		; 7.06709e-310
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?test@@YAXPEAH@Z DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?init@@YAXPEAH@Z DQ 00000620900010901r	; 5.32557e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DQ	00000820400011319r		; 7.06285e-310
	DD	imagerel __GSHandlerCheck
	DD	030H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ?test@@YAXPEAH@Z
_TEXT	SEGMENT
number$ = 48
?test@@YAXPEAH@Z PROC					; test, COMDAT
; File C:\Users\aiden\source\repos\Process\Process\Main.cpp
; Line 5
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
$LN2@test:
; Line 8
	mov	rax, QWORD PTR number$[rsp]
	mov	r8d, DWORD PTR [rax]
	mov	rdx, QWORD PTR number$[rsp]
	lea	rcx, OFFSET FLAT:$SG4294967289
	call	printf
; Line 9
	mov	ecx, 450				; 000001c2H
	call	QWORD PTR __imp_Sleep
; Line 10
	lea	rcx, OFFSET FLAT:$SG4294967288
	call	QWORD PTR __imp_system
	npad	1
; Line 11
	jmp	SHORT $LN2@test
; Line 12
	add	rsp, 40					; 00000028H
	ret	0
?test@@YAXPEAH@Z ENDP					; test
_TEXT	ENDS
END
